// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostStateHandlerFunc turns a function with the right signature into a post state handler
type PostStateHandlerFunc func(PostStateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostStateHandlerFunc) Handle(params PostStateParams) middleware.Responder {
	return fn(params)
}

// PostStateHandler interface for that can handle valid post state params
type PostStateHandler interface {
	Handle(PostStateParams) middleware.Responder
}

// NewPostState creates a new http.Handler for the post state operation
func NewPostState(ctx *middleware.Context, handler PostStateHandler) *PostState {
	return &PostState{Context: ctx, Handler: handler}
}

/*PostState swagger:route POST /state postState

PostState post state API

*/
type PostState struct {
	Context *middleware.Context
	Handler PostStateHandler
}

func (o *PostState) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostStateParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
