// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/darwinnn/TestTask/src/models"
)

// NewPostStateParams creates a new PostStateParams object
// no default values defined in spec.
func NewPostStateParams() PostStateParams {

	return PostStateParams{}
}

// PostStateParams contains all the bound params for the post state operation
// typically these are obtained from a http.Request
//
// swagger:parameters postState
type PostStateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: header
	*/
	SourceType string
	/*
	  Required: true
	  In: body
	*/
	StateObj *models.StateObj
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostStateParams() beforehand.
func (o *PostStateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindSourceType(r.Header[http.CanonicalHeaderKey("Source-Type")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.StateObj
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("stateObj", "body"))
			} else {
				res = append(res, errors.NewParseError("stateObj", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.StateObj = &body
			}
		}
	} else {
		res = append(res, errors.Required("stateObj", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSourceType binds and validates parameter SourceType from header.
func (o *PostStateParams) bindSourceType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("Source-Type", "header")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("Source-Type", "header", raw); err != nil {
		return err
	}

	o.SourceType = raw

	if err := o.validateSourceType(formats); err != nil {
		return err
	}

	return nil
}

// validateSourceType carries on validations for parameter SourceType
func (o *PostStateParams) validateSourceType(formats strfmt.Registry) error {

	if err := validate.Enum("Source-Type", "header", o.SourceType, []interface{}{"game", "server", "payment"}); err != nil {
		return err
	}

	return nil
}
